##consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
###consul注册中心地址
  cloud:
    consul:
      host: 192.168.20.100
      port: 8500
      discovery:
        #hostname: consul服务端ip
        hostname: 192.168.1.13
        service-name: ${spring.application.name}
