server:
  port: 83

spring:
  application:
    name: nacos-order-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.126:8848    #注册到nacos的IP地址和端口号

#消费者将要去访问的微服务名称(注册成功进nacos的微服务提供者)
server-url:
  nacos-user-service: http://nacos-payment-provider

