server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      default-binder: rabbit   #消息组件类型
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设置“text/plain”
          #binder:  defaultRabbit # 设置要绑定的消息服务的具体设置
          binder:
            - ${spring.cloud.stream.binders.defaultRabbit} # 设置要绑定的消息服务的具体设置
          group: queue1   #指定队列名，未指定时自动生成，多个服务使用同一个队列名，可避免消息重复消费

  rabbitmq:   #配置要绑定的rabbitmq服务信息
    host: 192.168.20.120
    port: 5672
    username: admin
    password: admin


eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds:  2 #设置心跳时间，(默认是30秒)
    lease-expiration-duration-in-seconds: 5 #间隔时间 (默认是30秒)
    instance-id: receive-8802.com    #在信息列表时显示主机名称
    prefer-ip-address: true     #访问的裤脚变为ip地址